### ISSUE TITLE
Can't use Get match by id API

### ISSUE THREAD

**Issue by catoxinn** [Henrik-3/valorant-labs#24]
Hi. I tried the website API for VALORANT.
https://docs.henrikdev.xyz/valorant-api.html

I can't use the API with 410 deprecated error.
- Get Tracker Profile
- Get matches from user

I can use the other API
- Get PUUID from user
- Get MMR from user

To reproduce the issue,
1. Get Leaderboard and gameName/tagLine
2. to use Get PUUID from user and succeeded.
3. to use get matches from user and failed.

**Comment by Henrik-3** [comment]
All Tracker Profiles are disabled because of legal reasons. To see which endpoints are available switch to the following repository: https://github.com/Henrik-3/unofficial-valorant-api
