### ISSUE TITLE
Unable to edit autorole

### ISSUE THREAD

**Issue by teknogeek** [Henrik-3/valorant-labs#34]
![image](https://user-images.githubusercontent.com/2267004/195933598-8c883543-645d-4ad3-b663-7ff0619e0371.png)

There is a bug which causes the embed message to get edited to an ephemeral reply. This makes it impossible to right-click and edit the autorole embed message

**Comment by Henrik-3** [comment]
If no not ephemeral message is send make sure the bot has `SEND_MESSAGES` Permissions

**Comment by Henrik-3** [comment]
I need to add a permissions check for that

**Comment by teknogeek** [comment]
Yes, it has `SEND_MESSAGES`, but the message is edited here: https://github.com/Henrik-3/valorant-labs/blob/v4/commands/slash/autoroles.js#L113

instead of sending a new message

**Comment by Henrik-3** [comment]
There is a difference between interactions and a normal message that is send in the channel which is here: https://github.com/Henrik-3/valorant-labs/blob/v4/commands/slash/autoroles.js#L79

**Comment by Henrik-3** [comment]
Can u send me the channel id where u try to execute the command?

**Comment by teknogeek** [comment]
1027598970781966406

**Comment by Henrik-3** [comment]
Seems like there was a conflict between the djs dev version and the normal one, can u try to execute the command again?

**Comment by teknogeek** [comment]
There we go,  fixed now. Thank you!
