### ISSUE TITLE
Servers down?

### ISSUE THREAD

**Issue by vialcollet** [Henrik-3/valorant-labs#37]
Hi and thanks for the great work.

I installed the bot a few days ago but it seems that I can't get stats.
Here is the message I get: 

![image](https://user-images.githubusercontent.com/4971086/207377093-71735b21-0e86-4fa6-8f7e-8e4367f7c093.png)

Any insights?

Thanks

**Comment by vialcollet** [comment]
Could it be related to latest Valorant patch 5.12?

**Comment by Henrik-3** [comment]
Maybe, but i don't think so. Could you tell me the name of the player you want to lookup?

**Comment by vialcollet** [comment]
DarkZelus#0866

I tried the bot from Tracker Network and it fails too (and also with other players)...

**Comment by vialcollet** [comment]
From the above screenshot, I see two different issues.  
The first one is related to elements being downloaded and the second one is just saying that the app doesn't answer anymore.

**Comment by Henrik-3** [comment]
That bug report was a big one, i probably now have to check all database entries for that one issue.
I had a code flaw where the code wasn't properly updated to the new data scheme so there are now many entries where the best agent wasn't count correctly

**Comment by Henrik-3** [comment]
Fix is deployed, pls recheck. It could be that the "best" agent stat on the right is not fully correct bc of that issue

**Comment by vialcollet** [comment]
Wow !!! It's working :)

That was quick! You are amazing!

Thanks and congrats for your work.

**Comment by vialcollet** [comment]
Hey I forgot to close the issue yesterday...
