### ISSUE TITLE
Patch notes not up to date

### ISSUE THREAD

**Issue by vialcollet** [Henrik-3/valorant-labs#38]
Hi again

Patch notes are still showing 5.10 instead of 5.12.

Command: 
```
/patch
```

![image](https://user-images.githubusercontent.com/4971086/207402275-09b16b55-ef94-46f9-b6f5-929718b43023.png)

**Comment by Henrik-3** [comment]
Hey, thats more a riot issue then mine, riot hasn't tagged this updates as a patch note:
Update v5.12
![image](https://user-images.githubusercontent.com/43936184/207407510-b66ffa59-884e-4624-97b2-806713baecbe.png)

Update v.5.10
![image](https://user-images.githubusercontent.com/43936184/207407562-96250bef-f49a-4272-ba61-ad7159ea3516.png)

**Comment by vialcollet** [comment]
Oh taht makes sense :)
All good we can close then.
